
import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.URISyntaxException;
import java.nio.file.Files;
import java.nio.file.LinkOption;
import java.nio.file.Paths;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Ekjot Singh
 */
public class Crack extends javax.swing.JFrame implements Runnable {

    File dicdir;
    String dicname;
    String userID, percentages, time;
    int percentage, speed;
    Thread t;

    /**
     * Creates new form Crack
     */
    public Crack() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ta = new java.awt.TextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        userIDtf = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        percentagetf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        speedtf = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        startbut = new javax.swing.JButton();
        stopbut = new javax.swing.JButton();
        pausebut = new javax.swing.JButton();
        resumebut = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        pb = new javax.swing.JProgressBar();
        timel = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ta.setEditable(false);
        ta.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel1.setText("Enter UserID :");

        userIDtf.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        userIDtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userIDtfActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Comic Sans MS", 1, 16)); // NOI18N
        jButton5.setText("Choose Dictionary");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel2.setText("Percentage :");

        percentagetf.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        percentagetf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                percentagetfActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel3.setText("Speed :");

        speedtf.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        speedtf.setText("40");
        speedtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                speedtfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(userIDtf, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(percentagetf)
                            .addComponent(speedtf))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userIDtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(percentagetf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(speedtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        startbut.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        startbut.setText("Start");
        startbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startbutActionPerformed(evt);
            }
        });

        stopbut.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        stopbut.setText("Stop");
        stopbut.setEnabled(false);
        stopbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopbutActionPerformed(evt);
            }
        });

        pausebut.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        pausebut.setText("Pause");
        pausebut.setEnabled(false);
        pausebut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pausebutActionPerformed(evt);
            }
        });

        resumebut.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        resumebut.setText("Resume");
        resumebut.setEnabled(false);
        resumebut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resumebutActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jButton4.setText("RESET");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(startbut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pausebut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resumebut))
            .addComponent(stopbut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startbut)
                    .addComponent(pausebut)
                    .addComponent(resumebut))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stopbut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pb.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        pb.setFocusable(false);
        pb.setStringPainted(true);

        timel.setFont(new java.awt.Font("Comic Sans MS", 1, 16)); // NOI18N
        timel.setText("Time left :");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pb, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
            .addComponent(timel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(timel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ta, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startbutActionPerformed
        percentage = Integer.parseInt(percentagetf.getText().trim().equals("") ? "0" : percentagetf.getText().trim());
        speed = Integer.parseInt(speedtf.getText().trim().equals("") ? "40" : speedtf.getText().trim());
        if (!(percentage >= 0 && percentage <= 100)) {

            ta.setText("Percentage out of range");
        } else if (speed < 1) {
            ta.setText("Speed out of range");
        } else {
            startbut.setEnabled(false);

            pausebut.setEnabled(true);
            stopbut.setEnabled(true);
            //resumebut.setEnabled(false);

            userID = userIDtf.getText().trim();
            t = new Thread(this, "RunningNode");
            t.start();
        }

    }//GEN-LAST:event_startbutActionPerformed

    private void userIDtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userIDtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userIDtfActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        //     fc.setEnabled(true);
//fcf.setVisible(true);
File currdir = null,selectdir = null;
        JFileChooser fc = new JFileChooser();
        fc.setApproveButtonText("Select");
        //fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        // fc.setAcceptAllFileFilterUsed(false);

        try {
currdir=new File(Crack.class.getProtectionDomain().getCodeSource().getLocation().toURI().getPath());
            fc.setCurrentDirectory(currdir);

        } catch (URISyntaxException ex) {
            Logger.getLogger(Crack.class.getName()).log(Level.SEVERE, null, ex);
        }
        int i = fc.showOpenDialog(this);

        if (i == JFileChooser.APPROVE_OPTION) {
            selectdir=fc.getSelectedFile();
            dicname = selectdir.getName();
           
        }
        startbut.setEnabled(true);

        try {
            currdir=new File(currdir.getParentFile().getAbsolutePath().concat("\\"+dicname));
            copyFile(selectdir, currdir);
             dicdir = currdir.getParentFile();
        }catch (IOException ex) {
            Logger.getLogger(Crack.class.getName()).log(Level.SEVERE, null, ex);
            
        }
        // TODO add your handling code here:
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void pausebutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pausebutActionPerformed
        pausebut.setEnabled(false);
        startbut.setEnabled(false);
        resumebut.setEnabled(true);

        t.suspend();
    }//GEN-LAST:event_pausebutActionPerformed

    private void stopbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopbutActionPerformed
        stopbut.setEnabled(false);
        pausebut.setEnabled(false);
        resumebut.setEnabled(false);
        t.stop();

        // TODO add your handling code here:
    }//GEN-LAST:event_stopbutActionPerformed

    private void resumebutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resumebutActionPerformed
        resumebut.setEnabled(false);
        pausebut.setEnabled(true);
        stopbut.setEnabled(true);
        t.resume();        // TODO add your handling code here:
    }//GEN-LAST:event_resumebutActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        userIDtf.setText("");
        ta.setText("");
        startbut.setEnabled(false);
        pausebut.setEnabled(false);
        resumebut.setEnabled(false);
        stopbut.setEnabled(false);
        pb.setValue(0);
        speedtf.setText("40");
        timel.setText("Time left :");
        percentagetf.setText("");
        if (!t.getState().equals("NEW")) {
            t.stop();

        }

        dicdir = null;
        dicname = null;
        userID = null;

// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void percentagetfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_percentagetfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_percentagetfActionPerformed

    private void speedtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_speedtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_speedtfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Crack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Crack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Crack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Crack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Crack().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton pausebut;
    private javax.swing.JProgressBar pb;
    private javax.swing.JTextField percentagetf;
    private javax.swing.JButton resumebut;
    private javax.swing.JTextField speedtf;
    private javax.swing.JButton startbut;
    private javax.swing.JButton stopbut;
    private java.awt.TextArea ta;
    private java.awt.Label timel;
    private javax.swing.JTextField userIDtf;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        //throw new UnsupportedOperationException("Not supported yet.");

        ProcessBuilder p = null;
        p = new ProcessBuilder("cmd.exe", "/C", "node main.js " + userID + " " + dicname + " " + percentage + " " + speed);
        p.directory(dicdir);
        //   p.directory(new File("C:\\Users\\Ekjot Singh\\Desktop\\yoyo"));
        try {
            Process r = p.start();
            BufferedReader br = new BufferedReader(new InputStreamReader(r.getInputStream()));
            StringBuffer sb = new StringBuffer();
            String line;
            while ((line = br.readLine()) != null) {

                if (line.length() > 10) {
                    if (line.substring(0, 3).equals("err")) {

                        int i = 7;//err at <password> <progress>
                        while (line.charAt(++i) != '%') {

                        }

                        ta.append("\n\n\nCONNECTION LOST. Succesfully run " + line.substring(7, i + 1) + ".\nYou can still Resume.\n");
                        pausebut.doClick();
                    } else {
                        int i = 0;

                        if (line.charAt(i = 1) == '%' || line.charAt(i = 2) == '%' || line.charAt(i = 3) == '%') {
                            percentages = line.substring(0, i);
                            if (!percentages.equals("NaN")) {
                                pb.setValue(Integer.parseInt(percentages));

                            }
                            line = line.substring(i + 2);

                        }

                        i = -1;
                        if (line.length() > 5 && line.substring(0, 4).equals("Time")) {

                            while (line.charAt(++i) != '|') {

                            }
                            time = line.substring(0, i);
                            timel.setText(time);
                            line = line.substring(i + 1);

                        }

                    }

                }
                ta.append(line + "\n");
                Thread.sleep(10);

            }
            // br.close();
            int result = r.waitFor();
           

            pausebut.setEnabled(false);
            resumebut.setEnabled(false);
            stopbut.setEnabled(false);
            if(result==0){timel.setText("Process Complete.");}
            else{timel.setText("Error Occured.");}

            // TODO add your handling code here:
        } catch (IOException ex) {
            Logger.getLogger(Crack.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InterruptedException ex) {
            Logger.getLogger(Crack.class.getName()).log(Level.SEVERE, null, ex);
        }

//To change body of generated methods, choose Tools | Templates.
    }

    public void copyFile(File source, File dest) throws IOException {

        Files.copy(source.toPath(), dest.toPath());
    }

}
